# -*- coding: utf-8 -*-
"""hw2-dl-018282420.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiMyfaQ-RYvEkLcp4g3o02ckj-S0JfD1
"""

!pip install -q transformers[torch] datasets evaluate rouge_score gradio accelerate sentencepiece
print("Dependencies installed.")

import torch
import evaluate
import pandas as pd
import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    pipeline
)
import gradio as gr

MODEL_Base = "t5-small"
MODEL_Compare_1 = "facebook/bart-large-cnn"
MODEL_Compare_2 = "google/pegasus-xsum"
DATASET_NAME = "samsum"

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Running on: {device}")

DATASET_NAME = "knkarthick/samsum"

dataset = load_dataset(DATASET_NAME)
tokenizer = AutoTokenizer.from_pretrained(MODEL_Base)

def preprocess_function(examples):
    inputs = ["summarize: " + doc for doc in examples["dialogue"]]

    model_inputs = tokenizer(inputs, max_length=1024, truncation=True)
    labels = tokenizer(text_target=examples["summary"], max_length=128, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = dataset.map(preprocess_function, batched=True)
print("Data preprocessing complete.")

import gc
import torch
import numpy as np
import evaluate
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq
)

rouge = evaluate.load("rouge")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    if isinstance(predictions, tuple):
        predictions = predictions[0]
    predictions = np.array(predictions)
    labels = np.array(labels)
    pad_token_id = 0
    predictions = np.where(predictions < 0, pad_token_id, predictions)
    labels = np.where(labels < 0, pad_token_id, labels)
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v * 100, 4) for k, v in result.items()}

models_to_train = [
    "t5-small",
    "facebook/bart-base",
    "sshleifer/distilbart-cnn-6-6"
]

saved_model_paths = {}
device = "cuda" if torch.cuda.is_available() else "cpu"

for model_name in models_to_train:
    print(f"Processing: {model_name}")

    # Clean Memory
    torch.cuda.empty_cache()
    gc.collect()

    # Load
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    # Dynamic Preprocessing
    prefix = "summarize: " if "t5" in model_name else ""

    def preprocess_function_dynamic(examples):
        inputs = [prefix + doc for doc in examples["dialogue"]]
        model_inputs = tokenizer(inputs, max_length=1024, truncation=True)
        labels = tokenizer(text_target=examples["summary"], max_length=128, truncation=True)
        model_inputs["labels"] = labels["input_ids"]
        return model_inputs

    print(f"Tokenizing data for {model_name}...")
    tokenized_data = dataset.map(preprocess_function_dynamic, batched=True)

    # Training Arguments
    output_dir = f"./finetuned_{model_name.replace('/', '_')}"

    training_args = Seq2SeqTrainingArguments(
        output_dir=output_dir,
        report_to="none",
        eval_strategy="steps",
        eval_steps=100,
        learning_rate=2e-5,
        per_device_train_batch_size=4,
        per_device_eval_batch_size=4,
        weight_decay=0.01,
        save_total_limit=1,
        num_train_epochs=1,
        predict_with_generate=True,
        fp16=(device=="cuda"),
        logging_steps=50,
    )

    # Trainer
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_data["train"].select(range(2000)),
        eval_dataset=tokenized_data["test"].select(range(200)),
        tokenizer=tokenizer,
        data_collator=DataCollatorForSeq2Seq(tokenizer, model=model),
        compute_metrics=compute_metrics,
    )

    # Train
    print(f"Training {model_name}...")
    trainer.train()

    # Save
    save_path = f"./saved_{model_name.replace('/', '_')}"
    trainer.save_model(save_path)
    tokenizer.save_pretrained(save_path)
    saved_model_paths[model_name] = save_path

    print(f"Finished {model_name}. Saved to {save_path}")

    # Cleanup
    del model
    del trainer
    del tokenizer
    torch.cuda.empty_cache()

print("\n\nAll models trained successfully!")
print("Saved Paths:", saved_model_paths)

from transformers import pipeline
pipelines = {}

for original_name, saved_path in saved_model_paths.items():
    print(f"Loading {original_name} from {saved_path}...")
    pipelines[original_name] = pipeline("summarization", model=saved_path, device=0 if device=="cuda" else -1)

print("Pipelines ready.")

# Cell 10+11: Multi-Metric Comparison (R1, R2, RL)
import gc
import torch
import pandas as pd
import matplotlib.pyplot as plt
import evaluate
from transformers import pipeline

metric = evaluate.load("rouge")
test_subset = dataset["test"].select(range(100))
device = 0 if torch.cuda.is_available() else -1

comparison_targets = [
    {"name": "t5-small", "path": "./saved_t5-small", "prefix": "summarize: "},
    {"name": "facebook/bart-base", "path": "./saved_facebook_bart-base", "prefix": ""},
    {"name": "sshleifer/distilbart-cnn-6-6", "path": "./saved_sshleifer_distilbart-cnn-6-6", "prefix": ""}
]

records_multi = []
for target in comparison_targets:
    model_name = target["name"]
    save_path = target["path"]
    prefix = target["prefix"]
    print(f"Processing {model_name}")
    pipe = pipeline("summarization", model=model_name, device=device)
    preds = [pipe(prefix + t, max_length=128, truncation=True)[0]['summary_text'] for t in test_subset["dialogue"]]
    scores = metric.compute(predictions=preds, references=test_subset["summary"], use_stemmer=True)

    records_multi.append({
        "Model": model_name,
        "State": "Base",
        "ROUGE-1": scores["rouge1"] * 100,
        "ROUGE-2": scores["rouge2"] * 100,
        "ROUGE-L": scores["rougeL"] * 100
    })
    del pipe
    pipe = pipeline("summarization", model=save_path, device=device)
    preds = [pipe(prefix + t, max_length=128, truncation=True)[0]['summary_text'] for t in test_subset["dialogue"]]
    scores = metric.compute(predictions=preds, references=test_subset["summary"], use_stemmer=True)

    records_multi.append({
        "Model": model_name,
        "State": "Fine-Tuned",
        "ROUGE-1": scores["rouge1"] * 100,
        "ROUGE-2": scores["rouge2"] * 100,
        "ROUGE-L": scores["rougeL"] * 100
    })
    del pipe
    gc.collect()
    torch.cuda.empty_cache()

import matplotlib.pyplot as plt

metrics = ["ROUGE-1", "ROUGE-2", "ROUGE-L"]
colors = ['#ff9999', '#99ff99']

print(f"Generating {len(metrics)} Separate Graphs")

for m in metrics:
    pivot = df_multi.pivot(index="Model", columns="State", values=m)
    fig, ax = plt.subplots(figsize=(10, 6))

    pivot.plot(kind='bar', ax=ax, color=colors, edgecolor='black', width=0.7)

    ax.set_title(f"Impact of Training on {m} Performance", fontsize=16, fontweight='bold')
    ax.set_ylabel(f"{m} Score (0-100)", fontsize=12)
    ax.set_xlabel("Model Architecture", fontsize=12)
    ax.grid(axis='y', linestyle='--', alpha=0.3)
    plt.xticks(rotation=0)
    plt.legend(title="Model State", fontsize=10)

    for p in ax.patches:
        if p.get_height() > 0:
            ax.annotate(f"{p.get_height():.1f}",
                        (p.get_x() + p.get_width() / 2., p.get_height()),
                        ha='center', va='bottom',
                        fontsize=11, fontweight='bold',
                        xytext=(0, 5), textcoords='offset points')

    plt.tight_layout()
    plt.show()
    print("-" * 50)

import gradio as gr
from transformers import pipeline
if 'pipelines' not in globals():
    pipelines = {}
    print("Loading models for UI...")
    for name, path in saved_model_paths.items():
        pipelines[name] = pipeline("summarization", model=path, device=0 if torch.cuda.is_available() else -1)

def generate_comparison(dialogue):
    results = []
    for model_name in saved_model_paths.keys():
        pipe = pipelines[model_name]
        input_text = ("summarize: " + dialogue) if "t5" in model_name else dialogue
        output = pipe(input_text, max_length=100, min_length=10, truncation=True)
        results.append(output[0]['summary_text'])

    return tuple(results)

model_names_list = list(saved_model_paths.keys())
example_dialogue = """
Doctor: Hi, how are you feeling today?
Patient: I have a terrible headache and a sore throat.
Doctor: How long have you had these symptoms?
Patient: About three days now.
Doctor: Okay, let me check your temperature. It seems you have a slight fever.
Patient: Do I need antibiotics?
Doctor: Not yet. I'll prescribe some rest and fluids first. Come back if it gets worse.
"""

iface = gr.Interface(
    fn=generate_comparison,
    inputs=gr.Textbox(lines=10, placeholder="Paste a conversation here...", label="Input Dialogue", value=example_dialogue),
    outputs=[
        gr.Textbox(label=f"Model 1: {model_names_list[0]} (Fine-Tuned)"),
        gr.Textbox(label=f"Model 2: {model_names_list[1]} (Fine-Tuned)"),
        gr.Textbox(label=f"Model 3: {model_names_list[2]} (Fine-Tuned)", max_lines=10)
    ],
    title="AI Summarization Arena: Multi-Model Comparison",
    description="Compare how 3 different fine-tuned architectures summarize the same conversation.",
    theme="default"
)

iface.launch(share=True)